spring:
  application:
    name: bandi

  datasource:
    url: jdbc:postgresql://db-bandi.cpc4uswu8hst.ap-northeast-2.rds.amazonaws.com:5432/ssafy
    username: postgres
    password: byeoljalie102
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: 3.35.115.111
      port: 6379
      password: 'strongPassword'

  session:
    redis:
      namespace: custom:session

  jpa:
    show-sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
